services:
  db:
    image: mysql:8.0
    container_name: mi-mysql-db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 12341234
      MYSQL_DATABASE: pysentinel
      MYSQL_USER: user
      MYSQL_PASSWORD: 123123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: